### ISSUE TITLE
Doesn't work anymore

### ISSUE THREAD

**Issue by marco-prontera** [google-marketing-solutions/performance-psi-tracker#18]
Hello, I would like to warn you that the script no longer works, a few months ago it worked fine but now it no longer works. Has something happened?

Thank you!

**Comment by xpfgg** [comment]
Thanks Marco for the feedback! 

Just seeing this! I don't think this project is still maintained, but wanted to follow-up on this one.
I was involved in creating the second version of the tracker, and would suggest to try out the latest version that I just published: https://docs.google.com/spreadsheets/d/1RIJRfXYX0acXO0WTMjH8aQxMmdLqT1Qg5ZhNcn3hV6M/edit?usp=sharing
It is marked as "15th of April" and should work out of the box as long as you have a PSI (or CrUX) API key.
(The current version at https://github.com/google-marketing-solutions/performance-psi-tracker/tree/v2 is from the 3rd of November 2023, adding this addendum there). 

If you need further troubleshooting, feel free to paste the logs from `Extensions > Apps Script > Executions` that should contain the different issues faced by the tracker. I remember V1 being particularly impacted by breaking changes, for example https://developers.google.com/speed/docs/insights/release_notes#aug-8,-2023 

Hoping this helps!

Xavier
